### ISSUE TITLE
Implement Artwork Offer

### ISSUE THREAD

**Issue by stephaneK123** [ajcatindig/iSining#11]
![image](https://user-images.githubusercontent.com/11825845/197268353-027cfdde-1a78-4a80-9577-1b7a9cd4fce1.png)
--need to work on this

**Comment by ajcatindig** [comment]
Already done, kindly check the main branch as I've already merged the latest updates.

**Comment by ajcatindig** [comment]
In my latest update, viewing all the detail screens are already done. What's left to do now is implement the make an offer, and hire artist.

**Comment by stephaneK123** [comment]
--most ui + logic taken care of by @ajcatindig
