### ISSUE TITLE
Home Screen - UI

### ISSUE THREAD

**Issue by ajcatindig** [ajcatindig/iSining#2]
Home screen contents will be Artist of the Month and Artwork of the Month. 
- Topbar and bottom bar already done

Photo for reference:
![image](https://user-images.githubusercontent.com/75460782/191339409-8d1ec797-335d-4fe2-8634-a4ab690ea9be.png)

There will just 2 images in the home screen then an article type of description for that image.

**Comment by stephaneK123** [comment]
alright, on this! making a branch called sk_homescreen to add this

**Comment by ajcatindig** [comment]
Finished
